name: GitHub Actions test

run-name: ${{github.actor}} is testing GitHub Actions

on: [push]

jobs:
  Welcome-to-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the job was automaticly triggered by ${{github.event_name}} event."
      - run: echo "the job is running on ${{runner.os}} os."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files from repository
      - run: ls ${{github.workspace}}
      - run: echo "This job status is ${{job.status}}"
      
